# Generated by Django 5.2.6 on 2026-01-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='description',
            new_name='title',
        ),
    ]
